services:
  postgresql:
    image: postgres:15.3
    volumes:
      - chess-app:/var/lib/postgresql
    environment:
      - POSTGRES_USER=chess_admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chess_db
    ports:
      - 5432:5432
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgresql://chess_admin:password@localhost:5432/chess_db
volumes:
  chess-app: